// Copyright 2026 and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package types

import "encoding/json"

type CrawlDetalhesAcaoDetalhesAcaoItem struct {
	Markdown   json.RawMessage `json:"markdown"`
	StatusCode int             `json:"status_code"`
}

type CrawlListarAcoesItem struct {
	Markdown json.RawMessage `json:"markdown"`
	Tables   json.RawMessage `json:"tables"`
}
